-- Script generated by SimpleSpy - credits to exx#9394
if true then
local args = {
     [1] = "EndMatchGame",
     [2] = {
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card15] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card1] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card4] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card6] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card10] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card14] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card11] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card3] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card8] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card7] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card17] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card5] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card18] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card2] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card16] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card13] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card12] = {
             ["Matched"] = true
         },
         [game:GetService("Players").LocalPlayer.PlayerGui.ScreenGui.MatchThePet.Pets.Container.Main.Card9] = {
             ["Matched"] = true
         }
     }
 }
 
 game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer(unpack(args))
end
